server:
  port: 8761

#application name
spring:
  application:
    name: ead-service-registry

#evita que o eureka busque uma configuracao dele mesmo para nao ser cliente dela mesma
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false